### PR TITLE
move allowances Map from Feline class to avoid possible deadlock

### LINKED ISSUE #18: possible deadlock in com.spotify.feline.Feline with static initializer and 'allowances' Map
We have seen a few reports internally recently of what appears to be a deadlock within the Feline library, with thread dumps that look like the following:

the main thread is deep in executing the static initializer of `Feline` via a call to `com.spotify.feline.FelineMetricsRecorder.install()`:

```
"main" #1 prio=5 os_prio=0 cpu=4519.08ms elapsed=658.07s tid=0x00007f28a002b000 nid=0x7 waiting on condition  [0x00007f28a705b000]
   java.lang.Thread.State: RUNNABLE
	at java.lang.Class.forName0(java.base@11.0.15/Native Method)
	at java.lang.Class.forName(java.base@11.0.15/Class.java:398)
	at sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(java.base@11.0.15/CoreReflectionFactory.java:114)
	at ...
	at java.lang.Class.getGenericSuperclass(java.base@11.0.15/Class.java:949)
	at net.bytebuddy.description.type.TypeDescription$Generic$LazyProjection$ForLoadedSuperClass.resolve(TypeDescription.java:6570)
	at ...
	at net.bytebuddy.agent.builder.AgentBuilder$Default.doInstall(AgentBuilder.java:10916)
	at net.bytebuddy.agent.builder.AgentBuilder$Default.installOn(AgentBuilder.java:10842)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$Delegator.installOn(AgentBuilder.java:12583)
	at com.spotify.feline.Feline.<clinit>(Feline.java:225)
	at com.spotify.feline.FelineMetricsRecorder.install(FelineMetricsRecorder.java:84)
	at com.spotify.feline.FelineMetricsRecorder.install(FelineMetricsRecorder.java:75)
```

and multiple other threads which were spawned from `main` prior to installing Feline are `in Object.wait()` with a lambda from `com.spotify.feline.Feline` at the top of the stack trace:

```
"New I/O worker #9" #33 daemon prio=5 os_prio=0 cpu=88.19ms elapsed=655.07s tid=0x00007f28a2bc1800 nid=0x32 in Object.wait()  [0x00007f27f9f6b000]
   java.lang.Thread.State: RUNNABLE
	at com.spotify.feline.Feline$$Lambda$363/0x00000008004ccc40.matches(Unknown Source)
	at net.bytebuddy.agent.builder.AgentBuilder$RawMatcher$ForElementMatchers.matches(AgentBuilder.java:1833)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.doTransform(AgentBuilder.java:11870)
	at ...
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$ByteBuddy$ModuleSupport.transform(Unknown Source)
	at sun.instrument.TransformerManager.transform(java.instrument@11.0.15/TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(java.instrument@11.0.15/InstrumentationImpl.java:563)
	at java.lang.ClassLoader.defineClass1(java.base@11.0.15/Native Method)
	at java.lang.ClassLoader.defineClass(java.base@11.0.15/ClassLoader.java:1017)
	at java.security.SecureClassLoader.defineClass(java.base@11.0.15/SecureClassLoader.java:174)
	at jdk.internal.loader.BuiltinClassLoader.defineClass(java.base@11.0.15/BuiltinClassLoader.java:800)
	at jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(java.base@11.0.15/BuiltinClassLoader.java:698)
	at jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(java.base@11.0.15/BuiltinClassLoader.java:621)
	- locked <0x0000000724c99990> (a java.lang.Object)
	at jdk.internal.loader.BuiltinClassLoader.loadClass(java.base@11.0.15/BuiltinClassLoader.java:579)
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(java.base@11.0.15/ClassLoaders.java:178)
	at java.lang.ClassLoader.loadClass(java.base@11.0.15/ClassLoader.java:522)
	...
```

```
"endpoint-change-notifier-9" #46 daemon prio=5 os_prio=0 cpu=9.60ms elapsed=654.94s tid=0x00007f28a2bf5800 nid=0x3f in Object.wait()  [0x00007f27f935f000]
   java.lang.Thread.State: RUNNABLE
	at com.spotify.feline.Feline$$Lambda$363/0x00000008004ccc40.matches(Unknown Source)
	at net.bytebuddy.agent.builder.AgentBuilder$RawMatcher$ForElementMatchers.matches(AgentBuilder.java:1833)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.doTransform(AgentBuilder.java:11870)
	at ...
	at sun.instrument.InstrumentationImpl.transform(java.instrument@11.0.15/InstrumentationImpl.java:563)
	at java.lang.ClassLoader.defineClass1(java.base@11.0.15/Native Method)
	at java.lang.ClassLoader.defineClass(java.base@11.0.15/ClassLoader.java:1017)
	at java.security.SecureClassLoader.defineClass(java.base@11.0.15/SecureClassLoader.java:174)
	at jdk.internal.loader.BuiltinClassLoader.defineClass(java.base@11.0.15/BuiltinClassLoader.java:800)
	at jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(java.base@11.0.15/BuiltinClassLoader.java:698)
	at jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(java.base@11.0.15/BuiltinClassLoader.java:621)
	- locked <0x00000007275497b0> (a java.lang.Object)
	at jdk.internal.loader.BuiltinClassLoader.loadClass(java.base@11.0.15/BuiltinClassLoader.java:579)
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(java.base@11.0.15/ClassLoaders.java:178)
	...
```

It seems likely that the `com.spotify.feline.Feline$$Lambda$363` corresponds to the lambda in https://github.com/spotify/futuristic-feline/blob/e7de5ca34dd3a0a8f3843da2aeb08eac7cd50816/feline/src/main/java/com/spotify/feline/Feline.java#L216-L218 since that is the only lambda implementing the bytebuddy `ElementMatcher` interface.

Our best theory so far is that:

1. during application startup, a number of modules are started launching threads to do various things
1. a module which sets up `com.spotify.feline.FelineMetricsRecorder.install()` is executed, invoking the static initializer in `com.spotify.feline.Feline`
1.  while the `main` thread is executing Feline's static initializer which configures the bytebuddy AgentBuilder, other threads doing their work causes new classes to be loaded,  triggering the transformers in the bytebuddy agent - while it is in the process of being installed via the call to `AgentBuilder.installOn(instrumentation)` [here](https://github.com/spotify/futuristic-feline/blob/e7de5ca34dd3a0a8f3843da2aeb08eac7cd50816/feline/src/main/java/com/spotify/feline/Feline.java#L225) - and since the `ElementMatcher` instance we have passed into `AgentBuilder` for filtering types to transform involves executing a lambda defined in the `Feline` class, these threads are blocked waiting for the `Feline` class to finish being initialized 
   - this behavior fits in with the "initialization lock" mentioned in https://docs.oracle.com/javase/specs/jls/se11/html/jls-12.html#jls-12.4.1 (although it is a little curious that this is represented in the thread dump as the thread having a RUNNABLE state but being `in Object.wait()`)

What isn't totally clear at this point is why `main` / `com.spotify.feline.Feline<clinit>` is blocked in `java.lang.Class.forName0(java.base@11.0.15/Native Method)`, preventing the static initializer from finishing, which would unblock the other threads - or how to reliably reproduce the problem.

### PR DESCRIPTION
**Pull request by mattnworb**
This is an attempt to fix #18 by simply moving the Map out of the Feline class, so that when bytebuddy checks to see if a type matches the filter there is no need to load or access `com.spotify.feline.Feline`. My thought is then that any thread doing something that causes bytebuddy to invoke methods in an `AllowancesTransformer` instance has no need to wait for `com.spotify.feline.Feline` to finish being initialized.

 I don't feel 100% confident this fixes the problem until a reliable way to reproduce #18 can be found.

### CODE REVIEW

File: feline/src/main/java/com/spotify/feline/Feline.java [hunk 1]
```diff
@@ -32,7 +31,7 @@
 /** Detects blocking calls to @link CompletableFuture and notifies registered consumers. */
 public class Feline {
 
-  private static final Map<String, Set<String>> allowances = new ConcurrentHashMap<>();
+  private static final AllowancesTransformer allowancesTransformer = new AllowancesTransformer();
```
Comment (caesar-ralf) [inline feline/src/main/java/com/spotify/feline/Feline.java:34]: I think this falls under the same problem sadly, because it's a static field within `Feline`. I try something later, but I think we will need to remove this static and move to inside the `AllowancesTransformer`

Comment (caesar-ralf) [reply feline/src/main/java/com/spotify/feline/Feline.java:34]: created #20 to show what I meant

Comment (TheIndifferent) [reply feline/src/main/java/com/spotify/feline/Feline.java:34]: This field is explicitly passed into Agent builder, so ByteBuddy will never have to circle back to this field (like it was in case of lambda), so I actually think this would work 🤔

Comment (caesar-ralf) [reply feline/src/main/java/com/spotify/feline/Feline.java:34]: isn't the problem to access any static field? Although I see what you mean, as the lambda won't try to access the `allowances` it still trying to access this `allowancesTransformer`, which will be locked until the static initiation stops. Moving completely to another class removes the "competition" for static resources from this class

Comment (TheIndifferent) [reply feline/src/main/java/com/spotify/feline/Feline.java:34]: I think if we expand lambda to actual class instance it would be more visible, it will be something like this:
```
.type(new ElementMatcher<TypeDescription>() {
    public boolean matches(final TypeDescription typeDescription) {
        return Feline.allowances.containsKey(it.getName());
    }
})
```

Which basically means that when ByteBuddy will be evaluating the lambda - the lambda will need to access the `Feline` class again.

In the Matt's code, there is no reference back to `Feline` when the `ElementMatcher` is evaluated, so that I believe should work 🤔

Comment (mattnworb) [reply feline/src/main/java/com/spotify/feline/Feline.java:34]: what @TheIndifferent talks about here is exactly my line of thinking. The current code passes a reference to a static method/field to `AgentBuilder.type(..)` (which happens on the `main` thread) and when another thread does something that causes the bytebuddy transformer to be invoked it has to call/access the field/method in `Feline`. 

The `javap` output for the class might help make that more clear, I posted that in https://github.com/spotify/futuristic-feline/issues/18#issuecomment-1205204282

Comment (caesar-ralf) [reply feline/src/main/java/com/spotify/feline/Feline.java:34]: alright, agreed. As we can't really replicate I will try to release a release candidate internally and see if any of the people that had the problem is willing to test it

**Review by caesar-ralf — APPROVED** [review]

File: feline/src/main/java/com/spotify/feline/Feline.java (hunk 1 above)
Comment (caesar-ralf) [reply feline/src/main/java/com/spotify/feline/Feline.java:34]: I don't have the powers to merge this, would you mind doing it @mattnworb?

File: feline/src/main/java/com/spotify/feline/AllowancesTransformer.java [hunk 2]
```diff
@@ -17,24 +17,44 @@
...
-  AllowancesTransformer(Map<String, Set<String>> allowances) {
-    this.allowances = allowances;
+  AllowancesTransformer() {
+    this.allowances = new ConcurrentHashMap<>();
+  }
+
+  void allow(final String className, final String methodName) {
+    allowances.compute(
+        className,
+        (key, allowances) -> {
```
Comment (protocol7) [inline feline/src/main/java/com/spotify/feline/AllowancesTransformer.java:46]: Nitpick: duplicated names, can we rename the local variable name?

Comment (mattnworb) [reply feline/src/main/java/com/spotify/feline/AllowancesTransformer.java]: done 👍

**Comment by mattnworb** [comment]
while we aren't 100% sure this solves #18 at this point, there should be no actual behavioral change to Feline itself here, so we are going to cut a release to deploy internally to see if the problems we have been seeing intermittently internally still occur.
